name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

variables:
- group: pypi-credentials
- name: isMaster
  value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

pool:
  vmImage: 'ubuntu-latest'


stages:

- stage: unitTests
  displayName: Run Unit Tests
  jobs:
  - job: unitTests
    displayName: Run Unit Tests
    strategy:
      matrix:
        Python37:
          PYTHON_VERSION: '3.7'
        Python38:
          PYTHON_VERSION: '3.8'
        Python39:
          PYTHON_VERSION: '3.9'
        Python310:
          PYTHON_VERSION: '3.10'


    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
        displayName: Use Python $(PYTHON_VERSION)

      - script: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry==1.4.1
        displayName: 'Install poetry 1.4.1'
      
      - script: python -m poetry install
        displayName: 'Install dependencies'
        
      - script: python -m poetry run python -m pytest
        displayName: 'Test with pytest'

- stage: build
  displayName: Build package and post to PyPI
  dependsOn: unitTests
  # Run only if previous stage succeeded. Don't run for tagging events
  condition: and(succeeded(), eq(variables.isMaster, true))

  jobs:
    - job: buildAndUpload
      displayName: Build and Upload to PyPI

      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.10'
        displayName: 'Use Python 3.10'

      - script: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry==1.4.1
        displayName: 'Install poetry 1.4.1'
      
      - script: python -m poetry install
        displayName: 'Install dependencies'
      
      - script: python -m poetry publish --build --username $(PYPI_USER) --password $(PYPI_TOKEN)
        
