[pytest]
markers =
    focus: what is being developed right now
    create_csv: create CSV
    create_parquet: tools to find oom
    validate_parquet: tools to find oom
    validate_parquet_duckdb: tools to find oom
    perf_new: performance test new
    perf_old: performance test old
    mem_viz: visualize memory usage
