[pytest]
markers =
    focus: what is being developed right now
    perf_init: performance test initialization
    perf_new: performance test new
    perf_old: performance test old
    create_parquet: tools to find oom
