name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python -
        poetry install

    - name: Run tests
      id: test
      run: poetry run pytest

  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: PyPI 
    needs: test
    if: success()
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python -
        poetry install

    - name: Build and publish
      run: poetry publish --build --username ${{ secrets.PYPI_USER }} --password ${{ secrets.PYPI_TOKEN }}
